# Generated by Django 5.2.1 on 2025-05-30 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno autora musí být vyplněno'}, help_text='Zadejte jméno autora', max_length=80, verbose_name='Jméno autora')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení autora musí být vyplněno'}, help_text='Zadejte příjmení autora', max_length=50, verbose_name='Příjmení autora')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('umrti', models.DateField(blank=True, null=True, verbose_name='Datum úmrtí')),
                ('biografie', models.TextField(blank=True, verbose_name='Životopis')),
                ('fotografie', models.ImageField(upload_to='autori', verbose_name='Fotografie')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoři',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh', models.CharField(error_messages={'blank': 'Nazev literárního druhu musí být vyplněn'}, help_text='Zadejte název literárního žánru', max_length=100, verbose_name='Literární druh')),
            ],
            options={
                'verbose_name': 'Literární druh',
                'verbose_name_plural': 'Literární druhy',
                'ordering': ['druh'],
            },
        ),
        migrations.CreateModel(
            name='Vydavatelstvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název vydavatelství je povinný údaj'}, help_text='Zadejte název vydavatelství', max_length=100, verbose_name='Název vydavatelství')),
                ('adresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa')),
            ],
            options={
                'verbose_name': 'Vydavatelství',
                'verbose_name_plural': 'Vydavatelství',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název žánru', max_length=20, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(error_messages={'blank': 'Titul knihy musí být vyplněn'}, help_text='Zadejte titul knihy', max_length=100, verbose_name='Titul knihy')),
                ('obsah', models.TextField(blank=True, help_text='Vložte obsah knihy', verbose_name='Obsah knihy')),
                ('pocet_stran', models.PositiveIntegerField(blank=True, help_text='Zadejte počet stran (max. 9999)', null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Počet stran')),
                ('rok_vydani', models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1500 - 2100)', null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání')),
                ('obalka', models.ImageField(upload_to='obalky', verbose_name='Obálka knihy')),
                ('cena', models.PositiveIntegerField(error_messages={'blank': 'Cena musí být vyplněna'}, help_text='Zadejte cenu knihy', verbose_name='Cena')),
                ('hodnoceni', models.PositiveIntegerField(blank=True, help_text='Hodnocení knihy -> 1 = špatné, 5 = skvělé', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Hodnocení')),
                ('autori', models.ManyToManyField(to='eshop.autor')),
                ('druh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.druh', verbose_name='Literarní druh')),
                ('vydavatelstvi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.vydavatelstvi', verbose_name='Vydavatelství')),
                ('zanry', models.ManyToManyField(to='eshop.zanr')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
                'ordering': ['titul'],
            },
        ),
    ]
