# Generated by Django 5.2.1 on 2025-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='autori', verbose_name='Fotografie'),
        ),
    ]
