# Generated by Django 5.2.1 on 2025-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_autor_fotografie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanr',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis žánru'),
        ),
    ]
